version: '3.6'
services:
  java:
    image: openjdk:14-slim
    platform: linux/amd64
    ports:
      - 8080:8080
      - 5005:5005
    tty: true
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    command: ./gradlew bootRun

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d/:/etc/mysql/conf.d